version: '3.9'

services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - '5432:5432'
    volumes:
      #- db:/var/lib/postgresql/data
      - ./db/postgres-data:/var/lib/postgresql/data
    networks:
      - local_network
  keycloak:
    depends_on:
      - postgres
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_IMPORT: ./DigitalMedia.json
      KC_DB: postgres
      KC_DB_PASSWORD: 1234
      KC_DB_USERNAME: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
    image: quay.io/keycloak/keycloak:18.0.0
    command: start-dev
    ports:
      - "8082:8080"
    restart: unless-stopped
    networks:
      - local_network
  eureka-server:
    container_name: eureka-server
    depends_on:
      - keycloak
    image: eureka-server
    ports:
      - "8761:8761"
    restart: always
    networks:
      - local_network
  gateway-service:
    container_name: gateway-service
    depends_on:
      - eureka-server
    image: gateway-service
    ports:
      - "9090:9090"
    restart: always
    environment:
      EUREKA_URL: http://eureka-server:8761/eureka
      KEYCLOAK_URL: http://keycloak:8080/
    networks:
      - local_network
  peliculas-service:
    container_name: peliculas-service
    depends_on:
      - eureka-server
    image: peliculas-service
    ports:
      - "8086:8086"
    restart: always
    environment:
       EUREKA_URL: http://eureka-server:8761/eureka
       KEYCLOAK_URL: http://keycloak:8080/
    networks:
      - local_network
  facturacion-service:
    container_name: facturacion-service
    depends_on:
      - eureka-server
    image: facturacion-service
    ports:
      - "8088:8088"
    restart: always
    environment:
      EUREKA_URL: http://eureka-server:8761/eureka
      KEYCLOAK_URL: http://keycloak:8080/
    networks:
      - local_network
  usuarios-service:
    container_name: usuarios-service
    depends_on:
      - eureka-server
    image: usuarios-service
    ports:
      - "8087:8087"
    restart: always
    environment:
       EUREKA_URL: http://eureka-server:8761/eureka
       KEYCLOAK_URL: http://keycloak:8080/
    networks:
      - local_network
  mongodb:
    image: mongo
    container_name: "mongodb"
    command: mongod --auth
    environment:
      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
    ports:
      - "27017:27017"
    networks:
      - local_network

networks:
  local_network: {}

volumes:
  db:



