server:
  port: 9090

spring:
  application:
    name: gateway-service
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri:  ${KEYCLOAK_URL:http://localhost:8082/}realms/${app.realm}
            authorization-uri: http://localhost:8082/realms/${app.realm}/protocol/openid-connect/auth
            token-uri: ${KEYCLOAK_URL:http://localhost:8082/}realms/${app.realm}/protocol/openid-connect/token
            user-info-uri: http://localhost:8082/realms/${app.realm}/protocol/openid-connect/userinfo
            jwk-set-uri: ${KEYCLOAK_URL:http://localhost:8082/}realms/${app.realm}/protocol/openid-connect/certs
        registration:
          gateway-api:
            scope: openid
            provider: keycloak
            client-id: api-gateway
            client-secret: 4zBdFyVh83njKccG03JAo37nSUawgDd6
            authorization-grant-type: authorization_code
            redirect-uri: 'http://localhost:9090/login/oauth2/code/keycloak'
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - TokenRelay
      routes:
        - id: moviesRoute
          #uri: http://localhost:8086
          uri: lb://peliculas-service
          #uri: http://peliculas-service:8086
          predicates:
            - Path=/movies/**
          filters:
            - StripPrefix=0
            - name: CircuitBreaker
              args:
                name: moviesService
                fallbackUri: forward:/fallback/movies
        - id: usersRoute
          #uri: http://localhost:8087
          uri: lb://usuarios-service
          #uri: http://usuarios-service:8087
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=0
            - name: CircuitBreaker
              args:
                name: usersService
                fallbackUri: forward:/fallback/users

# La ruta hacia facturacion-service no está incluída
# Según lo conversado en clase no se puede acceder al facturacion-service a través del gateway

app:
  realm: DigitalMedia

eureka:
  client:
    service-url:
      #defaultZone: http://localhost:8761/eureka/
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    info:
      enabled: true
info:
  app:
    name: ${spring.application.name}
    description: Gateway Service Proyecto Integrador Materia Especialización Backend II
    version: 1.0.0

logging:
  level:
    org:
      springframework:
        security: DEBUG