INSERT INTO public.bill (ID_BILL, CUSTOMER_BILL, PRODUCT_BILL, TOTAL_PRICE,BILLING_DATE)
VALUES (RANDOM_UUID(), 'userprovider', 'courses/Java', 500,'2022-09-25');
INSERT INTO public.bill (ID_BILL, CUSTOMER_BILL, PRODUCT_BILL, TOTAL_PRICE,BILLING_DATE)
VALUES (RANDOM_UUID(), 'userclient', 'courses/Java', 500,'2022-09-28');
INSERT INTO public.bill (ID_BILL, CUSTOMER_BILL, PRODUCT_BILL, TOTAL_PRICE,BILLING_DATE)
VALUES (RANDOM_UUID(), 'userclient', 'courses/Java', 500,'2022-10-05');
INSERT INTO public.bill (ID_BILL, CUSTOMER_BILL, PRODUCT_BILL, TOTAL_PRICE,BILLING_DATE)
VALUES (RANDOM_UUID(), 'useradmin', 'courses/Java', 500,'2022-10-15');
INSERT INTO public.bill (ID_BILL, CUSTOMER_BILL, PRODUCT_BILL, TOTAL_PRICE,BILLING_DATE)
VALUES (RANDOM_UUID(), 'user', 'courses/Java', 500,'2022-10-25');
INSERT INTO public.bill (ID_BILL, CUSTOMER_BILL, PRODUCT_BILL, TOTAL_PRICE,BILLING_DATE)
VALUES (RANDOM_UUID(), 'userclient', 'courses/Java', 500,'2022-10-26');
